#!/usr/bin/ruby

def fa(command)
  system "cd #{application};#{command};cd .."
end

application = ARGV[0]
system "git clone git://github.com/justinvt/rails.git"
system "mv rails #{application}"

db_file = File.join(application,"config/database.yml")
db_config = File.read(db_file).gsub("myrails",application)
f = File.open(db_file, "w+")
f.puts db_config
f.close

fa "rake db:create"
fa "rake db:migrate"
system "mate #{application}"

system "cd #{application};ruby script/server"
