development:
  hostname: db_primary
  adapter: mysql
  encoding: utf8
  database: myrails_development
  username: root
  password: 
  socket: /tmp/mysql.sock

test:
  hostname: db_primary
  adapter: mysql
  encoding: utf8
  database: myrails_test
  username: root
  password: 
  socket: /tmp/mysql.sock

production:
  hostname: db_primary
  adapter: mysql
  encoding: utf8
  database: myrails_production
  username: root
  password:
  socket: /var/run/mysqld/mysqld.sock